### ISSUE TITLE
Hope to support NIST standard interfaces

### ISSUE THREAD

**Issue by inlmouse** [yui0/ugemm#1]
As we all know, BLAS is a kind of protocol. I holp this repo can support [NIST](http://www.netlib.org/blas/) standard interfaces in the future.

**Comment by yui0** [comment]
Thank you for your feedback.
I think so, too.
However, I developed this library for deep learning.
So I'll develop it as needed.
I do not know when it will be done.
I would like to support the NIST standard interface in the future.

**Comment by inlmouse** [comment]
Thxs for your reply.
